routes/web.php
<?php

use App\Models\User;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('admin.dashboard.home');
    return view('welcome');
    // return view('auth.login');
    // return view('admin.dashboard.home2');
    // return view('layouts.admin_login');

});



// Route::resource('customers','CustomerController');
Route::resource('customers',CustomerController::class);
Route::resource('products',ProductController::class);


Route::get('student','App\Http\Controllers\StudentController@index');
Route::post('student','App\Http\Controllers\StudentController@store')->name('student.store');
Route::get('student/{id}/edit', 'App\Http\Controllers\StudentController@edit')->name('student.edit');
Route::post('student/update', 'App\Http\Controllers\StudentController@update')->name('student.update');
Route::get('student/{id}/delete', 'App\Http\Controllers\StudentController@destroy')->name('student.delete');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/users',UserController::class);


Route::resource('/admin/customers',CustomerController::class);
Route::resource('/admin/products',ProductController::class);

Route::resource('/admin/tags',TagController::class);
Route::resource('/admin/brands', BrandController::class);

// Route::post('/admin/check_brand/{brand_id}',BrandController::class);
Route::post('/admin/check_brand', array('as' => '', 'uses' => 'BrandController@check_brand'));


Route::get('/roles',[App\Http\Controllers\PermissionController::class,'Permission']);

// Route::get('/roles', 'PermissionController@Permission');

Route::group(['middleware' => 'role:developer'], function() {
    Route::get('/admin', function() {
       return 'Welcome Admin';
    });

 });

app/Models/User.php
<?php

namespace App\Models;

use Psermission\HasPermissionsTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;


use Illuminate\Database\Eloquent\SoftDeletes;


class User extends Authenticatable
{
    use HasFactory, Notifiable;
    // use HasPermissionsTrait; //Import The Trait
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "users";

    protected $fillable = [
        'name',
        'email',
        'password',
        'profile_photo_path',
        'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    /**
     * Get the mobile number associated with the user.
     */
    public function mobile()
    {
        return $this->hasOne(Mobile::class);
        // note: we can also inlcude Mobile model like: 'App\Mobile'
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Mobile;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
    $this->middleware('auth');
    }

    public function index(){
        //

        $data=[];
        // $data['isTable']=true;
        $data['UserRegisters']=User::take(3)->get();
        $data['Users']=User::get();
        // dd($data);

        return view('admin.users.index',$data);
    }
    public function create()
    {

        $data=[];
        $data['isTable']=false;
        $data['UserRegisters']=User::take(3)->get();

        return view('admin.users.create',$data);
    }

    public function store(Request $request)
    {

        // if ($request->user()->can('store-users')) {
            $request->validate([
                'name' => 'required',
                'email' => 'required',
                'profile_photo_path' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);


            if($request->hasFile('profile_photo_path')){
                $image = $request->file('profile_photo_path');
                $imageName = 'user'.'-'.rand().'-'.time().'.'.$image->getClientOriginalExtension(); // generate new name
                $image->move(public_path('upload/users/'), $imageName);

            }
             User::create([
                'name'=>$request->name,
                'email'=>$request->email,
                'password'=>Hash::make($request->password),
                // 'bio'=>$request->bio,
                // 'facebook'=>$request->facebook,
                // 'twiter'=>$request->twiter,
                // 'telegram'=>$request->telegram,
                'created_at'=>$request->created_at,
                'profile_photo_path'=>'upload/users/'.$imageName
             ]);

             Toastr::success('User created successfully :)', 'Successfully');
            //  Toastr::success('Post added successfully :)','Success');

            return redirect()->route('users.index')
                ->with('success', 'User created successfully.');

        // }


    }

    public function addUserMobile()
    {
        $user = new User;
        $user->name = "Test Name";
        $user->email = "test@mnp.com";
        $user->password = Hash::make("12345678");
        $user->save();

        $mobile = new Mobile;
        $mobile->mobile = '123456789';
        $user->mobile()->save($mobile);
    }

    public function show($id)
    {

        // $data=[];
        // $data['isTable']=false;
        // $data['UserRegisters']=User::take(3)->get();


        $data=[];
        $data['isTable']=false;
        $data['UserRegisters']=User::take(3)->get();

        $data['user'] =User::where('id',$id)->firstOrFail();


        return view('admin.users.show',$data);
    }
    public function edit($id)
    {
        $data=[];
        $data['isTable']=false;
        $data['UserRegisters']=User::take(3)->get();

        $data['user'] =User::where('id',$id)->firstOrFail();

        return view('admin.users.edit',$data);

    }


    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $data = [
            'name' => $request->name,
            // 'slug' => $this->make_slug($request->title)."_".rand(),
            'email' => $request->email,
            // 'category_id' => $request->category_id,
            // 'password' => $request->seo,
            // 'meta' => $request->meta,
            // 'status' => $this->Status($request),
            'profile_photo_path' => 'upload/users/'.$this->UpdateImage($request,$id),
            // 'user_id' => Auth::user()->id
        ];
        $user->update($data);
        // $post->tags()->sync($request->tag);
        return redirect()->route('users.index')->with('success', 'You are update post successfully!!!');
    }



    public function destroy($id)
    {

        $User =User::where('id',$id)->firstOrFail();
        $User->delete();

        Toastr::success('User Delete successfully :)', 'Successfully');
        return redirect()->route('users.index')
            ->with('success', 'User deleted successfully');
    }





    protected function uploadImage(Request $request)
    {
        /*ការ​បញ្ចូល​រូប​ភាព​បាន​មួយ​ file */
        if ($request->hasFile('profile_photo_path')) {
            $image = $request->file('profile_photo_path');
            $image_name = rand() . '_user' . '.' . $image->getClientOriginalExtension(); // generate new name
            // $image_name = $image->getClientOriginalName(); // get the original name of image
            $uploadpath = public_path('upload/users/');
            if (!is_dir($uploadpath)) {
                mkdir($uploadpath, 0777, true);
            }
            $image->move($uploadpath, $image_name);
        } else {
            $image_name = null;
        }
        return $image_name;
    }
    protected function UpdateImage(Request $request, $id)
    {
        if ($request->hasFile('profile_photo_path')) {
            $image_path = public_path('upload/users/' . $this->OldImage($id));
            $image_path = public_path($this->OldImage($id));
			if (file_exists($image_path)) {
                // dd($image_path);
				unlink($image_path);
			}
			$image = $request->file('profile_photo_path');
			$image_name = 'user' . '_' . rand() . '_' . '.' . $image->getClientOriginalExtension(); // generate new name
			// $image_name = $image->getClientOriginalName(); // get the original name of image
			$uploadpath = public_path('upload/users/');
			if (!is_dir($uploadpath)) {
				mkdir($uploadpath, 0777, true);
			}
			$image->move($uploadpath, $image_name);
		} else {
			$image_name = $this->OldImage($id);
        }
        return $image_name;
    }
    protected function OldImage($id)
    {
        $old_image = User::findOrFail($id)->profile_photo_path;
        return $old_image;
    }



}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')
@section('title','Product List')

@push('css')


@endpush
@section('content')
 <!-- Content Header (Page header) -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add User</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
              <li class="breadcrumb-item active">Add user</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">User Information</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <section class="content" style="padding:15px;">
        @if(session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <form action="{{route('users.store')}}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="UserName">Full Name</label>
                            <input type="text" id="UserName" name="name" placeholder="SENG Sourng" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" placeholder="sourng@gmail.com" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" id="password" placeholder="12345678" name="password" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="Bio">Bio</label>
                            <textarea id="Bio" class="form-control" name="bio" rows="4"></textarea>
                        </div>

                    </div>
                    <!-- /.card -->
                </div>
                <div class="col-md-4">


                    <div class="form-group">
                        <strong>Profile Image:</strong>
                        <br>
                        <img onclick="javascript:changeProfile()" id="preview" class="preview" src="{{ asset('images/noimage.jpg') }}" width="100%" height="auto"/><br/>
                        <input type="file" name="profile_photo_path" id="image" class="image" style="display: none;"/>
                        {{-- <a href="javascript:changeProfile()" class="btn btn-success btn-xs imgupload" id="imgupload">Upload</a> | --}}
                        <a style="color: white; display:none;" href="javascript:removeImage()" class="btn btn-danger btn-xs remove" id="remove">Remove</a>

                    </div>



                    <div class="form-group">
                        <label for="roll">Roll</label>
                        <select class="form-control custom-select" id="roll" name="roll_id">
                            <option selected="" disabled="">Select one</option>
                            <option value="1">Admin</option>
                            <option value="2">Auther</option>
                        </select>
                    </div>

                </div>
            </div>
            <div class="card-footer">

                <button type="submit" class="btn btn-primary float-right ml-1">Save</button>
                {{-- <button type="submit" class="btn btn-danger float-right">Cancel</button> --}}
                <a href="{{route('users.index')}}" class="btn btn-danger float-right">Cancel</a>
            </div>
        </form>
    </section>

</div>

@endsection
@push('js')

<!-- Summernote -->
<script src="{{asset('admin/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>


<script>
    function changeProfile() {
      $('#image').click();
    }
    $('#image').change(function () {
      var imgPath = this.value;
      var ext = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
      if (ext == "gif" || ext == "png" || ext == "jpg" || ext == "jpeg") {
        $('#btn-remove').css('display','block');
        $('#btn-upload').text('Change');
        readURL(this);
      } else {
        alert("Please select image file (jpg, jpeg, png).");
      }
    });
    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.readAsDataURL(input.files[0]);
          reader.onload = function (e) {

            $('#preview').attr('src', e.target.result);
            $('#remove').css('display','block');
          };

      }
    }
    function removeImage() {
      $('#preview').attr('src',"{{ asset('images/noimage.jpg') }}");
      $('#remove').css('display','none');

    }
  </script>
@endpush

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@push('css')

    <link rel="stylesheet" href="{{asset('admin/plugins/summernote/summernote-bs4.css')}}">
    @endpush

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add User</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
              <li class="breadcrumb-item active">Add user</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Edit User Information</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <section class="content" style="padding:15px;">
        {{-- @if(session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif --}}

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


        <form action="{{ route('users.update',$user->id) }}" method="POST" enctype="multipart/form-data">
            @csrf

            @method('PUT')

            <div class="row">
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="UserName">Full Name</label>
                            <input type="text" id="UserName" name="name" value="{{$user->name}}" placeholder="SENG Sourng" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" value="{{$user->email}}" placeholder="sourng@gmail.com" class="form-control">
                        </div>

                        {{-- <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" id="password" value="{{$user->password}}" placeholder="12345678" name="password" class="form-control">
                        </div> --}}

                        <div class="form-group">
                            <label for="Bio">Bio</label>
                            <textarea id="Bio" class="form-control" value="{{$user->bio}}" name="bio" rows="4"></textarea>
                        </div>

                    </div>
                    <!-- /.card -->
                </div>
                <div class="col-md-4">


                    <div class="form-group">
                        <strong>Profile Image:</strong>
                        <br>
                        <img onclick="javascript:changeProfile()" id="preview" class="preview" src="{{$user->profile_photo_path==NULL?asset('upload/users/noimage.jpg'):asset($user->profile_photo_path)}}" width="100%" height="auto"/><br/>
                        <input type="file" name="profile_photo_path" id="image" class="image" style="display: none;"/>
                        {{-- <a href="javascript:changeProfile()" class="btn btn-success btn-xs imgupload" id="imgupload">Upload</a> | --}}
                        <a style="color: white; display:none;" href="javascript:removeImage()" class="btn btn-danger btn-xs remove" id="remove">Remove</a>

                    </div>



                    <div class="form-group">
                        <label for="roll">Roll</label>
                        <select class="form-control custom-select" id="roll" name="roll_id">
                            <option selected="" disabled="">Select one</option>
                            <option value="1">Admin</option>
                            <option value="2">Auther</option>
                        </select>
                    </div>

                </div>
            </div>
            <div class="card-footer">

                <button type="submit" class="btn btn-primary float-right ml-1">Save</button>
                {{-- <button type="submit" class="btn btn-danger float-right">Cancel</button> --}}
                <a href="{{route('users.index')}}" class="btn btn-danger float-right">Cancel</a>
            </div>
        </form>
    </section>

</div>

@endsection
@push('js')

<!-- Summernote -->
<script src="{{asset('admin/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>


<script>
    function changeProfile() {
      $('#image').click();
    }
    $('#image').change(function () {
      var imgPath = this.value;
      var ext = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
      if (ext == "gif" || ext == "png" || ext == "jpg" || ext == "jpeg") {
        $('#btn-remove').css('display','block');
        $('#btn-upload').text('Change');
        readURL(this);
      } else {
        alert("Please select image file (jpg, jpeg, png).");
      }
    });
    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.readAsDataURL(input.files[0]);
          reader.onload = function (e) {

            $('#preview').attr('src', e.target.result);
            $('#remove').css('display','block');
          };

      }
    }
    function removeImage() {
      $('#preview').attr('src',"{{ asset('images/noimage.jpg') }}");
      $('#remove').css('display','none');

    }
  </script>



@endpush

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('title','Tag List')

@push('css')

<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">

@endpush
@section('content')
 <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Tags</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Tags List</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Brand List</h5>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fas fa-wrench"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-right" role="menu">
                    <a href="#" class="dropdown-item">Action</a>
                    <a href="{{route('brands.create')}}" class="dropdown-item">Add New</a>
                    <a href="#" class="dropdown-item">Delete Selected</a>
                    <a class="dropdown-divider"></a>
                    <a href="#" class="dropdown-item">Update Info</a>
                  </div>
                </div>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div class="row">
                    @include('admin.users.list')
              </div>
              <!-- /.row -->
            </div>
            <!-- ./card-body -->
            <div class="card-footer">
              <div class="row">
                <div class="col-sm-3 col-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-success"><i class="fas fa-caret-up"></i> 17%</span>
                    <h5 class="description-header">$35,210.43</h5>
                    <span class="description-text">TOTAL REVENUE</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-warning"><i class="fas fa-caret-left"></i> 0%</span>
                    <h5 class="description-header">$10,390.90</h5>
                    <span class="description-text">TOTAL COST</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-success"><i class="fas fa-caret-up"></i> 20%</span>
                    <h5 class="description-header">$24,813.53</h5>
                    <span class="description-text">TOTAL PROFIT</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                  <div class="description-block">
                    <span class="description-percentage text-danger"><i class="fas fa-caret-down"></i> 18%</span>
                    <h5 class="description-header">1200</h5>
                    <span class="description-text">GOAL COMPLETIONS</span>
                  </div>
                  <!-- /.description-block -->
                </div>
              </div>
              <!-- /.row -->
            </div>
            <!-- /.card-footer -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </div><!--/. container-fluid -->
  </section>
  <!-- /.content -->

@endsection

@push('js')

 <!-- SweetAlert2 -->
 <script src="{{ asset('sweetalert2/sweetalert2.min.js') }}"></script>

<!-- DataTables -->
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

<!-- page script -->
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>

<script type="text/javascript">
    function deleteObject(id){
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          document.getElementById('frmItemDelete-'+id).submit();
          Swal.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          )
        }
      })
    }
</script>


{!! Toastr::message() !!}
@endpush

resources/views/admin/users/list.blade.php
			<!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                      <th>#ID</th>
                      <th>Picture</th>
                      <th>Name</th>
                    <th>Qty</th>
                    <th>Price</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>

                    @foreach ($Users as $users)
                    <tr>
                        <td>{{$users->id}}</td>
                        <td><img class="img-size-50" src="{{asset($users->profile_photo_path)}}" alt=""></td>
                        <td>
                            @if ($users->status ==1)
                                <i class="fas fa-circle text-success"></i>
                            @else
                                <i class="fas fa-circle text-danger"></i>
                            @endif {{$users->name}}
                        </td>
                        <td>dd</td>
                        <td>dd</td>
                        <td>
                            <a class="btn btn-danger btn-sm" href="javascript:deleteObject({{ $users->id }})">Delete</a>
                            <a class="btn btn-warning btn-sm" href="{{route('users.edit',$users->id)}}">Edit</a>
                            <form id="frmItemDelete-{{ $users->id }}" style="display: none" action="{{ route('users.destroy',$users->id) }}" role="form" method="POST" enctype="multipart/form-data">
                                {{-- {{ csrf_field() }}
                                {{ method_field('DELETE') }} --}}
                                @method('DELETE')
                                @csrf

                            </form>
                        </td>
                      </tr>
                    @endforeach

                  </tbody>
                  <tfoot>
                    <tr>
                        <th>#ID</th>
                        <th>Picture</th>
                        <th>Name</th>
                        <th>Qty</th>
                        <th>Price</th>
                        <th>Action</th>
                      </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->