routes/web.php
<?php

use App\Models\User;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('admin.dashboard.home');
    return view('welcome');
    // return view('auth.login');
    // return view('admin.dashboard.home2');
    // return view('layouts.admin_login');

});



// Route::resource('customers','CustomerController');
Route::resource('customers',CustomerController::class);
Route::resource('products',ProductController::class);


Route::get('student','App\Http\Controllers\StudentController@index');
Route::post('student','App\Http\Controllers\StudentController@store')->name('student.store');
Route::get('student/{id}/edit', 'App\Http\Controllers\StudentController@edit')->name('student.edit');
Route::post('student/update', 'App\Http\Controllers\StudentController@update')->name('student.update');
Route::get('student/{id}/delete', 'App\Http\Controllers\StudentController@destroy')->name('student.delete');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/admin/users',UserController::class);


Route::resource('/admin/customers',CustomerController::class);
Route::resource('/admin/products',ProductController::class);

Route::resource('/admin/tags',TagController::class);
Route::resource('/admin/brands', BrandController::class);

// Route::post('/admin/check_brand/{brand_id}',BrandController::class);
Route::post('/admin/check_brand', array('as' => '', 'uses' => 'BrandController@check_brand'));


Route::get('/roles',[App\Http\Controllers\PermissionController::class,'Permission']);

// Route::get('/roles', 'PermissionController@Permission');

Route::group(['middleware' => 'role:developer'], function() {
    Route::get('/admin', function() {
       return 'Welcome Admin';
    });

 });

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    protected $table = "brands";

    protected $fillable = [
        'name',
        'slug',
        'status',
        'user_id',
        'note',
        'image',
    ];


      public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Brand;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Auth;

class BrandController extends Controller
{
    public function __construct()
    {
    $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=[];
        $data['UserRegisters']=User::take(3)->get();
        $data['Brands']=Brand::get();


        return view('admin.brands.index',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data=[];
        $data['UserRegisters']=User::take(3)->get();
        $data['Brands']=Brand::get();

        return view('admin.brands.create',$data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->slug!=''){
            $slug=$this->make_slug($request->slug);
        }else{
            $slug=$this->make_slug($request->name);
        }
        Brand::create([
            'name'=>$request->name,
            'slug'=>$slug,
            'image'=>'noimage.jpg',
            'note'=>$request->note,
            'status' => $this->Status($request),
            'user_id'=>Auth::user()->id,
            'created_at'=>$request->created_at,

         ]);



         Toastr::success('Brand created successfully :)', 'Successfully');
         return redirect()->route('brands.create')
            ->with('success','Brand created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data=[];
        $data['UserRegisters']=User::take(3)->get();
        $data['Brands']=Brand::get();

        $data['BrandEdit']=Brand::findOrFail($id);

        return view('admin.brands.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $brand=Brand::findOrFail($id);
        if($request->slug!=''){
            $slug=$this->make_slug($request->slug);
        }else{
            $slug=$this->make_slug($request->name);
        }
        $brand->update([
            'name'=>$request->name,
            'slug'=> $slug,
            'status' => $this->Status($request),
            'user_id'=>Auth::user()->id,
            'updated_at'=>$request->updated_at,
        ]);

        Toastr::success('Brand Update successfully :)', 'Successfully');
         return redirect()->route('brands.index')
            ->with('success','Brand Update successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $Brand =Brand::where('id',$id)->firstOrFail();
        $Brand->delete();
        Toastr::success('Tag Delete successfully :)', 'Successfully');
        return redirect()->back();

    }
}

resources/views/admin/brands/create.blade.php
@extends('layouts.admin')
@section('title','Brand List')

@push('css')

<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">

@endpush
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add Tag</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
              <li class="breadcrumb-item active">Add Brand</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Tag Information</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <section class="content" style="padding:15px;">
        @if(session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <form action="{{route('brands.store')}}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div class="col-md-8">
                    @include('admin.brands.list2')

                </div>
                <div class="col-md-4">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="BrandName">Brand Name</label>
                            <input type="text" id="BrandName" name="name" placeholder="Enter Brand Name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="Slug">Slug</label>
                            <input type="text" id="Slug" name="slug" placeholder="name-of-your-brand" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="Slug">Note</label>
                            <input type="text" id="note" name="note" placeholder="name-of-your-note" class="form-control">
                        </div>


                        <div class="form-group">
                            <label for="status">Status</label>
                            <select class="form-control custom-select" id="status" name="status" required>
                                <option selected="" disabled="">Select one</option>
                                <option value="1">Active</option>
                                <option value="0">Not Active</option>
                            </select>
                        </div>

                    </div>
                    <!-- /.card -->
                </div>

            </div>
            <div class="card-footer">

                <button type="submit" class="btn btn-primary float-right ml-1">Save</button>
                {{-- <button type="submit" class="btn btn-danger float-right">Cancel</button> --}}
                <a href="{{route('brands.index')}}" class="btn btn-danger float-right">Cancel</a>
            </div>
        </form>
    </section>

</div>

@endsection
@push('js')
<!-- page script -->
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>


<!-- DataTables -->
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

<!-- Summernote -->
<script src="{{asset('admin/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>



@endpush

resources/views/admin/brands/edit.blade.php
@extends('layouts.admin')
@section('title','Brand List')

@push('css')

<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">

@endpush
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add Tag</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('/home')}}">Home</a></li>
              <li class="breadcrumb-item active">Add Brand</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Tag Information</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <section class="content" style="padding:15px;">
        @if(session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <form action="{{route('brands.update',$BrandEdit->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')

            <div class="row">
                <div class="col-md-8">
                    @include('admin.brands.list2')

                </div>
                <div class="col-md-4">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="BrandName">Brand Name</label>
                            <input type="text" id="BrandName" name="name" placeholder="Enter Brand Name" class="form-control" value="{{$BrandEdit->name}}" required>
                        </div>
                        <div class="form-group">
                            <label for="Slug">Slug</label>
                            <input type="text" id="Slug" name="slug" placeholder="name-of-your-brand" class="form-control" value="{{$BrandEdit->slug}}">
                        </div>
                        <div class="form-group">
                            <label for="Slug">Note</label>
                            <input type="text" id="note" name="note" placeholder="name-of-your-note" class="form-control" value="{{$BrandEdit->note}}">
                        </div>


                        <div class="form-group">
                            <label for="status">Status</label>
                            <select class="form-control custom-select" id="status" name="status" required>
                                <option selected="" disabled="">Select one</option>
                                <option {{$BrandEdit->status==1?'selected':''}} value="1">Active</option>
                                <option {{$BrandEdit->status==0?'selected':''}} value="0">Not Active</option>
                            </select>
                        </div>

                    </div>
                    <!-- /.card -->
                </div>

            </div>
            <div class="card-footer">

                <button type="submit" class="btn btn-primary float-right ml-1">Save</button>
                {{-- <button type="submit" class="btn btn-danger float-right">Cancel</button> --}}
                <a href="{{route('brands.index')}}" class="btn btn-danger float-right">Cancel</a>
            </div>
        </form>
    </section>

</div>

@endsection
@push('js')
<!-- page script -->
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>


<!-- DataTables -->
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

<!-- Summernote -->
<script src="{{asset('admin/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote()
  })
</script>



@endpush

resources/views/admin/brands/index.blade.php
@extends('layouts.admin')
@section('title','Tag List')

@push('css')

<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">

@endpush
@section('content')
 <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Tags</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Tags List</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Brand List</h5>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fas fa-wrench"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-right" role="menu">
                    <a href="#" class="dropdown-item">Action</a>
                    <a href="{{route('brands.create')}}" class="dropdown-item">Add New</a>
                    <a href="#" class="dropdown-item">Delete Selected</a>
                    <a class="dropdown-divider"></a>
                    <a href="#" class="dropdown-item">Update Info</a>
                  </div>
                </div>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div class="row">
                    @include('admin.brands.list')
              </div>
              <!-- /.row -->
            </div>
            <!-- ./card-body -->
            <div class="card-footer">
              <div class="row">
                <div class="col-sm-3 col-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-success"><i class="fas fa-caret-up"></i> 17%</span>
                    <h5 class="description-header">$35,210.43</h5>
                    <span class="description-text">TOTAL REVENUE</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-warning"><i class="fas fa-caret-left"></i> 0%</span>
                    <h5 class="description-header">$10,390.90</h5>
                    <span class="description-text">TOTAL COST</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-success"><i class="fas fa-caret-up"></i> 20%</span>
                    <h5 class="description-header">$24,813.53</h5>
                    <span class="description-text">TOTAL PROFIT</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-6">
                  <div class="description-block">
                    <span class="description-percentage text-danger"><i class="fas fa-caret-down"></i> 18%</span>
                    <h5 class="description-header">1200</h5>
                    <span class="description-text">GOAL COMPLETIONS</span>
                  </div>
                  <!-- /.description-block -->
                </div>
              </div>
              <!-- /.row -->
            </div>
            <!-- /.card-footer -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </div><!--/. container-fluid -->
  </section>
  <!-- /.content -->

@endsection

@push('js')

 <!-- SweetAlert2 -->
 <script src="{{ asset('sweetalert2/sweetalert2.min.js') }}"></script>

<!-- DataTables -->
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

<!-- page script -->
<script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>

<script type="text/javascript">
    function deleteObject(id){
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          document.getElementById('frmItemDelete-'+id).submit();
          Swal.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          )
        }
      })
    }
</script>

{{-- <script type="text/javascript">
    function deleteConfirmation(id) {
        swal({
            title: "Delete?",
            text: "Please ensure and then confirm!",
            type: "warning",
            showCancelButton: !0,
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel!",
            reverseButtons: !0
        }).then(function (e) {
            // alert("Hello");

            if (e.value === true) {
                var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

                $.ajax({
                    type: 'POST',
                    url: "{{url('admin/tags/delete')}}/" + id,
                    data: {_token: CSRF_TOKEN},
                    dataType: 'JSON',
                    success: function (results) {

                        if (results.success === true) {
                            Swal.fire("Done!", results.message, "success");
                            // Swal.fire('Hello world!')
                        } else {
                            Swal.fire("Error!", results.message, "error");
                        }
                    }
                });

            } else {
                e.dismiss;
            }

        }, function (dismiss) {
            return false;
        })
    }
</script> --}}

{!! Toastr::message() !!}
@endpush

resources/views/admin/brands/list.blade.php
			<!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#ID</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Created at</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>

                    @foreach ($Brands as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>
                            @if ($item->status ==1)
                                <i class="fas fa-circle text-success"></i>
                            @else
                                <i class="fas fa-circle text-danger"></i>
                            @endif {{$item->name}}

                       <?php
                            $count = \App\Models\Product::where('brand_id','=',$item->id)->count();
                        ?>
                        <span>({{$count}})</span>
                        </td>
                        <td>{{$item->slug}}</td>
                        <td>
                            {{-- {{$item->created_at}} --}}
                            <?php \Carbon\Carbon::setLocale('km') ?>
                            {{ \Carbon\Carbon::parse($item->created_at)->diffForHumans()}}

                        </td>
                        <td>

                            <a class="btn btn-danger btn-sm" href="javascript:deleteObject({{ $item->id }})">Delete</a>
                            <a class="btn btn-success btn-sm" href="{{route('brands.edit',$item->id)}}">Edit</a>
                            <form id="frmItemDelete-{{ $item->id }}" style="display: none" action="{{ route('brands.destroy',$item->id) }}" role="form" method="POST" enctype="multipart/form-data">
                                {{-- {{ csrf_field() }}
                                {{ method_field('DELETE') }} --}}
                                @method('DELETE')
                                @csrf

                            </form>
                        </td>
                      </tr>
                    @endforeach

                  </tbody>
                  <tfoot>
                    <tr>
                        <th>#ID</th>
                        <th>Name</th>
                        <th>slug</th>
                        <th>created at</th>
                        <th>Action</th>
                      </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->

resources/views/admin/brands/list2.blade.php
			<!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#ID</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Created at</th>

                  </tr>
                  </thead>
                  <tbody>

                    @foreach ($Brands as $item)
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>
                            @if ($item->status ==1)
                                <i class="fas fa-circle text-success"></i>
                            @else
                                <i class="fas fa-circle text-danger"></i>
                            @endif {{$item->name}}
                        </td>
                        <td>{{$item->slug}}</td>
                        <td>
                            <?php \Carbon\Carbon::setLocale('km') ?>
                            {{ \Carbon\Carbon::parse($item->created_at)->diffForHumans()}}

                        </td>

                      </tr>
                    @endforeach

                  </tbody>
                  <tfoot>
                    <tr>
                        <th>#ID</th>
                        <th>Name</th>
                        <th>slug</th>
                        <th>created at</th>

                      </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->